package com.adroited.aiterm.remote

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.cbor.Cbor
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test

class RemoteCommandsTest {
    @Test
    fun rustFlattenedSpineMapDecodesWorkingStatus() {
        // Generated by cargo run --example spine_wire_fixture. In particular,
        // serde(flatten) writes bf ... ff, not a definite-length event map.
        val page = RemoteCommands.spinePage(hex(
            "a56565706f636801646c697665f5686861735f6d6f7265f4697475726e5f6f70656ef5" +
                "666576656e747381bf63736571016565706f6368016a73657373696f6e5f6964697365" +
                "7373696f6e2d31656167656e7465636f64657862747309646b696e6465706861736565" +
                "706861736567776f726b696e676664657461696c6d72756e6e696e67207465737473ff",
        ))
        val store = SpineConversationStore()
        store.apply(page)
        assertEquals(true, store.live)
        assertEquals(true, store.turnOpen)
        assertEquals(SpinePhase.Working, store.phase)
        assertEquals("running tests", store.phaseDetail)
    }

    @Serializable
    private data class LegacySpineSnapshot(
        val epoch: Long,
        val live: Boolean,
        @SerialName("has_more") val hasMore: Boolean,
        val events: List<SpineEventWire>,
    )

    @Test
    fun terminalInputUsesTheExactStrictRustPayloadShape() {
        assertArrayEquals(
            hex(
                "a3" +
                    "667461625f69646174" +
                    "6d6174746163686d656e745f69646161" +
                    "64646174614178",
            ),
            RemoteCommands.input("t", "a", byteArrayOf('x'.code.toByte())),
        )
    }

    @Test
    fun sessionPreviewDecodesTheExactRustMessageShape() {
        val messages = RemoteCommands.sessionPreview(
            hex(
                "a1" +
                    "686d65737361676573" +
                    "81a3" +
                    "64726f6c656475736572" +
                    "64746578746568656c6c6f" +
                    "626174f6",
            ),
        )

        assertEquals(listOf(RemotePreviewMessage("user", "hello")), messages)
    }

    @Test
    fun sessionPreviewAcceptsTheRustTimestampField() {
        val messages = RemoteCommands.sessionPreview(
            hex(
                "a1" +
                    "686d65737361676573" +
                    "81a3" +
                    "64726f6c656475736572" +
                    "64746578746568656c6c6f" +
                    "62617474323032362d30382d32395432333a34323a30305a",
            ),
        )

        assertEquals("2026-08-29T23:42:00Z", messages.single().at)
    }

    @OptIn(ExperimentalSerializationApi::class)
    @Test
    fun spineSnapshotCarriesBoundsAndAcceptsAnOlderDesktopWithoutThem() {
        val cbor = Cbor {
            encodeDefaults = true
            useDefiniteLengthEncoding = true
        }
        val event = SpineEventWire(7, 3, "session-1", "codex", 9, "future_event")
        val current = RemoteCommands.spinePage(
            cbor.encodeToByteArray(
                SpineSnapshotWire.serializer(),
                SpineSnapshotWire(3, true, false, 4, 7, turnOpen = false, events = listOf(event)),
            ),
        )
        assertEquals(4, current.oldestSeq)
        assertEquals(7, current.latestSeq)
        assertEquals(false, current.turnOpen)

        val legacy = RemoteCommands.spinePage(
            cbor.encodeToByteArray(
                LegacySpineSnapshot.serializer(),
                LegacySpineSnapshot(3, true, false, listOf(event)),
            ),
        )
        assertEquals(0, legacy.oldestSeq)
        assertEquals(0, legacy.latestSeq)
        assertEquals(null, legacy.turnOpen)
    }

    @OptIn(ExperimentalSerializationApi::class)
    @Test
    fun webPreviewReplyAcceptsOnlyAnAvailableTicketPath() {
        val cbor = Cbor {
            encodeDefaults = true
            useDefiniteLengthEncoding = true
        }
        val ticket = "/v1/preview/${"a".repeat(43)}/"
        val available = RemoteCommands.webPreview(
            cbor.encodeToByteArray(WebPreviewWire.serializer(), WebPreviewWire(true, ticket)),
        )
        assertEquals(RemoteWebPreview(true, ticket), available)
        assertEquals(
            RemoteWebPreview(false, null),
            RemoteCommands.webPreview(
                cbor.encodeToByteArray(WebPreviewWire.serializer(), WebPreviewWire(false, null)),
            ),
        )
        assertThrows(RemoteProtocolException::class.java) {
            RemoteCommands.webPreview(
                cbor.encodeToByteArray(
                    WebPreviewWire.serializer(),
                    WebPreviewWire(true, "/v1/preview/../../secret/"),
                ),
            )
        }
    }

    @OptIn(ExperimentalSerializationApi::class)
    @Test
    fun sessionRosterDecodesNativeMetadataWithoutChangingTheSessionShape() {
        val session = RemoteSession(
            id = "session-1",
            agent = "codex",
            title = "Native roster",
            projectPath = "/work/aiterm",
            groupPath = "/work/aiterm",
            branch = "main",
            forked = false,
            background = false,
            forkParent = null,
            lastActive = 10,
        )
        val payload = Cbor {
            encodeDefaults = true
            useDefiniteLengthEncoding = true
        }.encodeToByteArray(
            SessionRosterWire.serializer(),
            SessionRosterWire(
                sessions = listOf(session),
                withFiles = listOf(session.id),
                stars = listOf(session.id),
                broughtIn = emptyMap(),
                activity = mapOf(session.id to "output"),
            ),
        )

        val roster = RemoteCommands.sessionRoster(payload)

        assertEquals(listOf(session), roster.sessions)
        assertEquals(setOf(session.id), roster.withFiles)
        assertEquals(setOf(session.id), roster.stars)
        assertEquals(mapOf(session.id to "output"), roster.activity)
    }

    @OptIn(ExperimentalSerializationApi::class)
    @Test
    fun markdownDocumentDecodesRustNativeBlocksAndRejectsUnknownKinds() {
        val cbor = Cbor { encodeDefaults = false; useDefiniteLengthEncoding = true }
        val document = RemoteMarkdownDocument(
            listOf(
                RemoteMarkdownBlock(
                    kind = "heading",
                    level = 2,
                    spans = listOf(RemoteMarkdownSpan("Native "), RemoteMarkdownSpan("Markdown", bold = true)),
                ),
                RemoteMarkdownBlock(
                    kind = "list_item",
                    checked = true,
                    spans = listOf(RemoteMarkdownSpan("done")),
                ),
            ),
        )
        val decoded = RemoteCommands.markdownDocument(cbor.encodeToByteArray(RemoteMarkdownDocument.serializer(), document))
        assertEquals(2, decoded.blocks.size)
        assertTrue(decoded.blocks.first().spans.last().bold)
        assertEquals(true, decoded.blocks.last().checked)

        val invalid = RemoteMarkdownDocument(listOf(RemoteMarkdownBlock(kind = "script")))
        assertThrows(RemoteProtocolException::class.java) {
            RemoteCommands.markdownDocument(cbor.encodeToByteArray(RemoteMarkdownDocument.serializer(), invalid))
        }
    }

    @OptIn(ExperimentalSerializationApi::class)
    @Test
    fun renderedSvgAndMarkdownSaveRepliesStayBounded() {
        val cbor = Cbor { encodeDefaults = true; useDefiniteLengthEncoding = true }
        val hash = ByteArray(32) { it.toByte() }
        val saved = RemoteCommands.markdownSaved(
            cbor.encodeToByteArray(MarkdownSavedWire.serializer(), MarkdownSavedWire("/work/notes.md", hash)),
        )
        assertEquals("/work/notes.md", saved.path)
        assertArrayEquals(hash, saved.sha256)

        val png = byteArrayOf(0x89.toByte(), 0x50, 0x4e, 0x47)
        val rendered = RemoteCommands.renderedFile(
            cbor.encodeToByteArray(RenderedFileWire.serializer(), RenderedFileWire("image/png", png)),
        )
        assertArrayEquals(png, rendered.data)
    }

    @Serializable
    private data class SessionRosterWire(
        val sessions: List<RemoteSession>,
        @SerialName("with_files") val withFiles: List<String>,
        val stars: List<String>,
        @SerialName("brought_in") val broughtIn: Map<String, String>,
        val activity: Map<String, String>,
    )

    @Serializable
    private data class WebPreviewWire(
        val available: Boolean,
        val path: String?,
    )

    @Serializable
    private data class MarkdownSavedWire(
        val path: String,
        @kotlinx.serialization.cbor.ByteString val sha256: ByteArray,
    )

    @Serializable
    private data class RenderedFileWire(
        val mime: String,
        @kotlinx.serialization.cbor.ByteString val data: ByteArray,
    )

    private fun hex(value: String): ByteArray =
        value.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
}
